import React from 'react';
import {useRouter} from 'next/router'
import Head from 'next/head'

export default function Game() {
    const router =useRouter();
    console.log(router)
    console.log(router.query)
    console.log(router.query.game)

    const {game, platform}=router.query;

    return (
        <div>
          <Head>
        <title>{game} | {platform}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <h1>Estamos en {game} plataforma: {platform}</h1>
        </div>
    )
}
